version: "3.8"

services:
  fertoolity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fertoolity_node
    ports:
      - "60000:5000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    restart: unless-stopped